name = "personal-website"
main = "worker.js"
compatibility_date = "2025-08-29"

send_email = [
    { name = "SEB"}
]

[assets]
directory = "./out/"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "test.ricardomarques.dev"
custom_domain = true

[observability]
enabled = true
