name = "personal-website"
main = "worker.js"
compatibility_date = "2025-08-29"

[assets]
directory = "./out/"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "test.ricardomarques.dev"
custom_domain = true

[observability]
enabled = true

send_email = [
     {type = "send_email", name = "SEB", destination_address = "{{ env.CONTACT_EMAIL }}"},
 ]

[vars]
CONTACT_EMAIL = "{{ env.CONTACT_EMAIL }}"