name = "personal-website"
main = "worker.js"
compatibility_date = "2025-08-29"

[assets]
directory = "./out/"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "test.ricardomarques.dev"
custom_domain = true

[observability]
enabled = true

[vars]
CONTACT_EMAIL = "${CONTACT_EMAIL}"

[[send_email]]
name = "SEB"
destination_address = "${CONTACT_EMAIL}"