version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.3.0
    steps:
        - run:
            name: Install LFTP
            command: |
                sudo apt-get update;
                sudo apt-get install lftp;

      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test -- --coverage

      - run:
          name: Build the Webapp
          command: npm run build

      - run:
          name: "Deploy to Hosting Service"
          command: lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ -X *.map -X php/ -X cv.pdf --reverse --verbose --delete build/ www/; bye"
