version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout

      - setup_remote_docker

      - aws-cli/setup

      - run:
          name: Run UI Tests
          command: make test_ui

      - run:
          name: Build the App image
          command: make build_image

      - run:
          name: "Deploy to ECS"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make deploy
            fi

orbs:
  aws-cli: circleci/aws-cli@1.0.0
