export default [
  {
    company: "OakNorth Bank",
    startingDate: "January 2024",
    endingDate: "Now",
    jobTitle: "lead software engineer",
    location: "London",
    roles: [
      "Led and mentored the Core Banking team, comprised of 4 engineers (2 seniors, 2 mid-level.",
      "Responsible for the integrity of the bank's ledger, safeguarding customer funds and maintaining accurate reconciliations. While designing and developing new banking products.",
      "Led the implementation of new transfer flows, enabling seamless transfers of customer funds between accounts with tens of millions of pounds in monthly throughput.",
      "Collaborated closely with Finance and Cash Operations teams to automate regulatory reporting and account reconciliation processes, ensuring precision and compliance with industry-wide standards."
    ],
    technologies: [
      "Python",
      "Kafka",
      "PostgreSQL",
      "BigQuery",
      "Docker",
      "AWS",
    ],
    url: "https://www.thousandeyes.com/",
  },
  {
    company: "ThousandEyes (Cisco)",
    startingDate: "July 2023",
    endingDate: "December 2023",
    jobTitle: "senior software engineer",
    location: "London",
    roles: [
      "Developed and maintained BigData ETL pipelines for both training and real-time anomaly detection, enriching telemetry data from customer networks to support adaptive early warning systems that autonomously learn and align with network usage patterns.",
    ],
    technologies: [
      "Java",
      "Kafka",
      "PostgreSQL",
      "Spark",
      "Airflow",
      "Docker",
      "AWS",
    ],
    url: "https://www.thousandeyes.com/",
  },
  {
    company: "Longshot Systems",
    startingDate: "November 2018",
    endingDate: "June 2023",
    jobTitle: "senior full stack developer",
    location: "London",
    roles: [
      "Led the UI development of internal and customer facing web UIs: including defining CI/CD workflows, selecting technologies, and UI/UX design.",
      "Ownership over greenfield full stack projects (React+Golang+Postgres), where I was responsible for all development phases, including: requirement gathering, architecture design, full stack implementation, deployment and maintenance.",
      "Spearheaded the introduction of Docker as the execution platform for Longshot’s microservices, in place of Systemd. Additionally, designed and developed a build & deployment CLI tool that streamlined the Docker development workflow. Which greatly facilitated the transition to Docker, from the developer’s perspective.",
      "Worked on various high throughput and event driven data processing applications. For example, one that aggregated sport information across different third-party systems (bookies) and produced internal representations, which abstracted the rest of the system from the various bookie-specific nomenclatures. This was by achieved by producing a proximity graph for sporting events that were closely related to one another, and required high amounts of integration/blackbox tests (harnessing docker-compose) to ensure ongoing reliability.",
    ],
    technologies: [
      "Golang",
      "React",
      "Typescript",
      "PostgreSQL",
      "Docker",
      "Node.js",
      "AWS",
    ],
    url: "https://www.longshotsystems.co.uk/",
  },
  {
    company: "Hyperglance",
    startingDate: "July 2014",
    endingDate: "October 2018",
    jobTitle: "senior full stack developer",
    location: "London",
    roles: [
      "Developed core modules for the Hyperglance JEE product. The latter spanned the full server-side architectural stack, ranging from JAX-RS Rest Endpoints, and EJB enhanced business-logic features, to JPA persistence components.",
      "Kick-started the conceptualization and development of Hyperglance’s Web GUI. This included selecting technologies, defining CI/CD pipelines, being in charge of best practices, API contracts between frontend and backend."
    ],
    technologies: [
      "Angular",
      "Node.js",
      "Java EE (Wildfly)",
      "PostgreSQL",
      "AWS",
    ],
    url: "https://www.hyperglance.com/",
  },
  {
    company: "Guidewire Software",
    startingDate: "November 2012",
    endingDate: "June 2014",
    jobTitle: "solutions consultant",
    location: "Dublin",
    roles: [
      "Partly designed, developed and maintained an efficient and fault-tolerant configuration of a multi-tiered J2EE Guidewire billing product on two tier one Insurance companies, that would later handle millions of dollars in early revenue.",
      "Designed and developed integration points (e.g., SOAP, JMS) between the client server application and external third-party services, that provided scalable and concurrent bidirectional data flows based on real-time monetary client transactions.",
    ],
    technologies: ["Java", "JMS", "SOAP", "Rest", "PostgreSQL"],
    url: "https://www.guidewire.com/",
  },
];
