export default [
  {
    company: "Longshot Systems",
    endingDate: "Now",
    jobTitle: "senior full stack developer",
    location: "London",
    roles: [
      "Lead the UI development of internal and customer facing web UIs: including defining CI/CD workflows, selecting technologies, and UI/UX design.",
      "Ownership over greenfield full stack projects (React+Golang+Postgres), where I was responsible for all development phases, including: requirement gathering, architecture design, full stack implementation, deployment and maintenance.",
      "Spearheaded the introduction of Docker as the execution platform for Longshot’s microservices, replacing the previous service manager (systemd). Additionally, designed and developed a build & deployment CLI tool that streamlined the Docker development workflow. Thus, greatly facilitating the transition to Docker, from the developer’s perspective.",
      "Worked on multiple high-frequency/low-latency integrations with third party Bookies. These integrations handled large trading volumes and had to be robust to external failures (e.g., crashes, bugs) while having to run 24/7 all year long.",
    ],
    startingDate: "Nov 2018",
    technologies: [
      "React",
      "Golang",
      "PostgreSQL",
      "Typescript",
      "Docker",
      "Webpack",
    ],
    url: "https://www.longshotsystems.co.uk/",
  },
  {
    company: "Trussle",
    endingDate: "Oct 2018",
    jobTitle: "senior full stack developer",
    location: "London",
    roles: [
      "Conceptualized and implemented v1.0 of a Typescript fraud-checker bot, on top of Node.js. The bot used data heuristics to compare new applications against, previously flagged, fraudulent ones and would automatically notify the internal compliance team, if need be.",
      "Implemented both the client side (React) and server side (Typescript) of an internal tool, used by Customer Success personnel, that replaced a non-GDPR compliant workflow. The tool allowed increased productivity while at the same time provided bigger visibility, into a critical part of the mortgage submission workflow.",
    ],
    startingDate: "Apr 2018",
    technologies: ["React", "Typescript", "PostgreSQL", "Node.js", "Webpack"],
    url: "https://trussle.com/",
  },
  {
    company: "Hyperglance",
    endingDate: "Mar 2018",
    jobTitle: "senior full stack developer",
    location: "London",
    roles: [
      "Enhanced the Hyperglance JEE server-side feature-base, by developing core modules. The latter spanned the full server-side architectural stack, ranging from JAX-RS Rest Endpoints, and EJB enhanced business-logic features, to JPA persistence components",
      "Kick-started conceptualization and development of Hyperglance’s Web GUI. This included selecting what technologies to use, defining a build used by developers and CI tools, developing the client’s architectural backbone (that integrated a WebGL module for data visualization, and outlining coding practices/standards. Moreover, was in charge of all technical aspects regarding the Web GUI and its integration with the Hyperglance backend. All the while being the only web developer on the team.",
      "Other responsibilities included: interviewing both frontend and backend developer candidates, attending conferences, speaking to customers, mentoring new-hires, and evaluating codebase health.",
    ],
    startingDate: "Jul 2014",
    technologies: [
      "AngularJs",
      "Javascript",
      "Three.js",
      "Java EE",
      "EJBs",
      "PostgreSQL",
      "Webpack",
      "Gradle",
      "Wildfly",
    ],
    url: "https://www.hyperglance.com/",
  },
  {
    company: "Guidewire Software",
    endingDate: "Jun 2014",
    jobTitle: "solutions consultant",
    location: "Dublin",
    roles: [
      "Partly designed, developed and maintained an efficient and fault-tolerant configuration of a multi-tiered J2EE Guidewire billing product on two tier one Insurance companies, that would later handle millions of dollars in early revenue.",
      "Designed and developed integration points (e.g., SOAP, JMS) between the client server application and external third-party services, that provided scalable and concurrent bidirectional data flows based on real-time monetary client transactions.",
      "Conceptualized and implemented a modular JUnit framework for populating Guidewire’s product database with test data. The framework improved the JUnit development productivity in 50%, on average.",
    ],
    startingDate: "Nov 2012",
    technologies: ["Java", "JMS", "SOAP", "Rest", "PostgreSQL"],
    url: "https://www.guidewire.com/",
  },
];
